### ISSUE TITLE
Saving variables for subsequent tests

### ISSUE THREAD

**Issue by montanaflynn** [mishushakov/teststep#1]
Hello, first of all this project looks great and really useful!

Now onto the question / suggestion, in my tests I would like to make requests that use data returned from previous requests. For example:

First I would create something:

Request: POST /product `{"name": "thing"}`
Response: 201 `{"id": "k2d8we", "price": "20"}`

The next request would need to use the ID field and maybe I'd like to assert something in the response as well based on a previous response.

Request: GET /product/{id}
Response: 200 `{"id": "k2d8we", "price": "20"}`

Another use case would be authentication. 

I would login like this:

Request: POST /user/login `{"username": "montanaflynn", "password: "hunter15"}`

The response would contain an access token that subsequest requests would need to use.

I'm not sure about the syntax for this, but I think setting something like this could work:

```yaml
name: Example # Test name
steps: # Steps

  - name: POST request
    endpoint: https://jsonplaceholder.typicode.com/posts
    method: POST
    headers:
      Content-Type: application/json
    match:
      res:
        status: 201
    data: |
      {
        "title": "title",
        "body": "body",
        "id": 123
      }
    variables:
      - name: postID
        body:
          type: json
          field: "ID"

  - name: GET request # Name
    endpoint: https://jsonplaceholder.typicode.com/posts/{postID} # Endoint
    method: GET # Method
    headers: # Headers
      Content-Type: application/json
    match: # Match
      res: # Match response (https://developer.mozilla.org/en-US/docs/Web/API/Response)
        status: 200
      body: # Match response body
        type: json # json or text
        data: |
          {
            "userId": 1,
            "id": 1,
            "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
            "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
          }
```

**Comment by mishushakov** [comment]
Hey,
glad you liked the project!

at the moment it is "stateless", meaning there is no state between the steps
however i would love to introduce this functionality once the project gets some more traction :)

thank you

**Comment by mishushakov** [comment]
Ok, i've added it, see https://github.com/mishushakov/teststep/commit/afdafe963b30427ce0c940079fdd11969d5bfc91

to try out see the examples
will document it tomorrow
feel free to give a star and share with your friends

bye bye

**Comment by montanaflynn** [comment]
Hi @mishushakov, thanks for the quick feedback and implementation!

I see the new example uses environment variables and mustache to replace the request. How would users be able to set variables based on a previous request response body / header? That's what I was most interested in and tried to explain with 2 use cases.

**Comment by montanaflynn** [comment]
Here's an example using the login / authorization use case:

```
name: Login Authorization
steps: 
  - name: Login
    endpoint: http://www.mocky.io/v2/5e3cd06d2d00004e00d95929
    method: POST
    headers:
      Content-Type: application/json
    match:
      res:
        status: 201          
    data: |
      {
        "username": "montanaflynn",
        "password": "hunter15"
      }
    variables:
      - name: accessToken
        body:
          type: json
          field: "access_token"

  - name: Get Posts
    endpoint: http://www.mocky.io/v2/5e3cd0ef2d0000ac00d9592a
    method: GET 
    headers:
      Authorization: Bearer Token {{accessToken}}
    match:
      res:
        status: 200
```
